package com.tematikhonov.cinelibrary.presentation

const val NAV_MAIN = "Main"
const val NAV_SPLASH = "Splash"
const val NAV_WELCOME = "Welcome"
const val NAV_LOGIN = "Login"
const val NAV_SIGN_UP = "SignUp"
const val NAV_HOME = "Home"
const val NAV_SEARCH = "Search"
const val NAV_FAVORITES = "Favorites"
const val NAV_PROFILE = "Profile"
const val NAV_MOVIE = "MovieDetails/{movieId}"
const val NAV_GALLERY = "MovieDetailsGallery/{movieId}"
const val NAV_PERSON = "Person/{personId}"
const val NAV_LANGUAGE = "Language"
const val NAV_HELP = "Help"
const val NAV_POLICIES = "Policies"
const val NAV_ABOUT = "About"